### ISSUE TITLE
Regex: ROOT

### ISSUE THREAD

**Issue by huiminlim** [AY1920S1-CS2103-F09-2/main#143]
![image](https://user-images.githubusercontent.com/43434313/67592124-7cf10680-f791-11e9-81ff-df48babadb7c.png)

Hi, just to check, 
I ran the following commands in the flow as shown in the notepad, with the following process in mind:
- Create empty deck
- create some cards
- change root directory
- export to root directory

![image](https://user-images.githubusercontent.com/43434313/67592544-96df1900-f792-11e9-9649-9c47b2b1939a.png)

I have some questions regarding UG updating in future:
- does it mean that enum response `ROOT` must be the first command during the start up to prevent data loss in the middle if you do not execute `export` command after creating decks?
i.e. do this 
(change root directory ->)Create empty deck -> create some cards -> change root directory
- Reason: it will overwrite your program state

**Comment by AHaliq** [comment]
The issue is the create command. It does not store the new deck into the state. See `dream.fcard.logic.respond.command.CreateCommand`.

Also Its not using responses for input. For some reason a new Scanner for cli input. It should be something like this:

https://gist.github.com/AHaliq/fdcc323090fd32eaecff6c1f867bcbaa

What i wrote is pseudocode but I hope you get the idea of using state to parse user input. If the implementation is still ambiguous let me know, ill implement the full proper create command and it can be used for future reference when others want to create their own responses for their features.

And Id like to emphasize that all user input must come from lambda argument, no where else, not even scanner.
